version: "3"
services:
    web:
        tty: true
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django_book_app
        ports:
            - "8020:8020"
        volumes:
            - .:/app
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8020"
        # environment:
        #     DB_HOST: db
        #     DB_NAME: test_db
        #     DB_USER: mysql
        #     DB_ROOT_PASSWORD: root
        #     DB_PASSWORD: mysql_pass
        # depends_on:
        #     - db
        
#     db:
#         image: mysql:8
#         environment:
#             MYSQL_ROOT_PASSWORD: root
#             #MYSQL_USER: root
#             # MYSQL_PASSWORD: 12345
#         ports:
#             - "3306:3306"
#         volumes: 
#             - ./data:/var/lib/mysql
       



      
# #     db:
# #         image: postgres:10-alpine
# #         environment:
# #             POSTGRES_DB: app
# #             POSTGRES_USER: postgres
# #             POSTGRES_PASSWORD: 12345
# #         ports:
# #             - "5432:5432"
# #         volumes:
# #             - /datadir:/var/lib/postgresql/data
# # volumes:
# #     datadir:



