apiVersion: v1
kind: Service
metadata:
  name: django-rest-service
spec:
  type: LoadBalancer
  selector:
    app: django-rest
  ports:
    - protocol: TCP
      port: 8020
      targetPort: 8020
      nodePort: 31000